export { default as DiseaseRepository } from './disease';
export { default as PatientRepository } from './patient';
export { default as JobRepository } from './job';
export { default as TumorRepository } from './tumor';
export { default as DrugRepository } from './drug';
export { default as MedicineRepository } from './medicine';
export { default as PathologyRepository } from './pathology';
export { default as ReasonRepository } from './reason';
export { default as LocationRepository } from './location';
